### PR TITLE
Escape the apostrophe characters in README

### PR DESCRIPTION
**Pull request by claytron5000**
Connects #22 
I'm not 100% sure this is causing the build issue on GitHub, but it looks like the likely issue.

### CODE REVIEW

**Comment by juliangruber** [comment]
hey, can you tell me why you are using jekyll with this README, so I fully understand the use case?

It looks to me though like this error is coming from the `{{a}` variables in the README.

**Comment by johnramsden** [comment]
@juliangruber the problem is is when building jekyll, problems like this occur:

```
Liquid Exception: 
Liquid syntax error (line 62): 
Variable '{{a}' was not properly terminated with regexp: 
/\}\}/ in node_modules/balanced-match/README.md
```

It looks like jekyll scanning the markdown and finds the problem. It would make sense to fix the problem here so that the issue doesn't occur for other people.

For anyone looking, a work around would be adding ```node_modules``` to jekyll's exclude option.

```
exclude:
  - node_modules
```

**Comment by juliangruber** [comment]
ok I understand the issue now. How big a change would it be to properly escape the README? If it's more than trivial, I'd rather add a section to the README about this though.

**Comment by claytron5000** [comment]
Very trivial, my PR here adds a backslash in front of the apostrophe.

**Comment by johnramsden** [comment]
@claytron5000 If I'm not mistaken the problem is actually the curly-braces, isn't it?

**Comment by jurra** [comment]
Will I have a problem if I have a javascript file at the root of the repo? They also have curly braces.

**Comment by juliangruber** [comment]
> For anyone looking, a work around would be adding node_modules to jekyll's exclude option.
>
> exclude:
>  - node_modules

This module's README is valid markdown, if tooling can't handle the `'` character then it's either misbuilt or misconfigured.

**Pull request closed without merging**
